version: '3'

networks:
  nfmc:

services:
  site:
    build:
      context: .
      dockerfile: docker-compose/nginx.dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - nfmc

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nfmc_laravel_oauth
      MYSQL_ROOT_PASSWORD: nfmc123
    networks:
      - nfmc

  php:
    build:
      context: .
      dockerfile: docker-compose/php.dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - nfmc

  composer:
    build:
      context: .
      dockerfile: ./docker-compose/composer.dockerfile
    container_name: composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - nfmc
    entrypoint: ['composer', '--ignore-platform-reqs']

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: docker-compose/php.dockerfile
    container_name: artisan
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - nfmc
